language: rust
addons:
  apt:
    packages:
      - libasound2-dev
      - libudev-dev
      - libssl-dev
env:
  global:
    - RUST_BACKTRACE=1
matrix:
  include:
    - rust: stable
      env: WASM=0
      script: cd ./jam_game && cargo check --examples --no-default-features
  include:
    - rust: stable
      env: WASM=0
      script: cd ./jam_game/tilemap && cargo check --examples --no-default-features && cargo test
  allow_failures:
    - rust: nightly
  fast_finish: true