language: rust
addons:
  apt:
    packages:
      - libasound2-dev
      - libudev-dev
      - libssl-dev
env:
  global:
    - RUST_BACKTRACE=1
jobs:
  include:
    - rust: stable
      os: linux
      env: WASM=0
      script: cd ./jam_game && cargo build
    - rust: stable
      os: linux
      env: WASM=0
      script: cd ./jam_game/tilemap && cargo test
    - rust: beta
      os: linux
      env: WASM=0
      script: cd ./jam_game && cargo build
    - rust: beta
      os: linux
      env: WASM=0
      script: cd ./jam_game/tilemap && cargo test