[package]
name = "jam_game"
version = "0.1.0"
authors = ["Jake McLeman <jake@mcleman.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicksilver = "0.3.20"
recs = "2.0.1"
