[package]
name = "tilemap"
version = "0.1.0"
authors = ["Jake McLeman <jake@mcleman.com>"]
edition = "2018"

[dependencies]
noise = "0.6.0"
quicksilver = "0.3.20"
lru = "0.4.0"

[dev-dependencies]
criterion = "0.3"
rand = "0.7.2"

[[bench]]
name = "map_perf_bench"
harness = false
