[package]
name = "tilemap"
version = "0.1.0"
authors = ["Jake McLeman <jake@mcleman.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noise = "0.6.0"
quicksilver = "0.3.20"
